version: '3'
services:
  web:
    image: few2012few/mamos-hub:lastest
    container_name: mamos
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/